server {
    listen 80;
    server_name ailaopo.online www.ailaopo.online;

    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }
}